name: Docker Build and Push


on:
  push:
    branches:
      - master
    paths:
      - src/DepartureBoard/*


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

  # The commit id
  COMMIT_ID: ${{ github.sha }}
  
  # A short version of the commit id
  COMMIT_ID_SHORT: ${GITHUB_SHA::7}

  IMAGE_NAME: ghcr.io/ch-lee/departure-board


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET 9.0 explicitly
      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short commit SHA
        run: echo "COMMIT_ID_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: src/DepartureBoard
          file: src/DepartureBoard/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID_SHORT }}